flask/database/database/app/main/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from flask_pagedown.fields import PageDownField


class ArticleForm(Form):
    title = StringField(label=u'标题', validators=[DataRequired()])
    body = PageDownField(label=u'正文', validators=[DataRequired()])
    submit = SubmitField(u'发表')


class CommentForm(Form):
    body = PageDownField(label=u'评论', validators=[DataRequired()])
    submit = SubmitField(u'发表')


class ReplyForm(Form):
    body = PageDownField(label=u'回复', validators=[DataRequired()])
    submit = SubmitField(u'发表')

flask/database/database/app/__init__.py
# -*- coding: utf-8 -*-
from flask import Flask, request
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, current_user
from os import path

base_url = path.abspath(path.dirname(__name__))
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app():
    app = Flask(__name__)

    Bootstrap(app)

    app.config.from_pyfile('config')
    app.config['SQLALCHEMY_DATABASE_URI'] = \
        'sqlite:///' + path.join(base_url, "data.sqlite")
    app.config['SQLALCHEMY_COMMIT_ON_TEARDOWN'] = True
    db.init_app(app)
    login_manager.init_app(app)
    from .auth.views import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')
    from .main.views import main as main_blueprint
    app.register_blueprint(main_blueprint)

    @app.template_test('current_link')
    def is_current_link(link):
        return link == request.path

    return app

flask/database/database/app/main/views.py
from flask import render_template, request, redirect, url_for, render_template_string
from flask import Blueprint
from ..models import Article, Comment, Reply
from .forms import ArticleForm, CommentForm, ReplyForm
from flask_login import login_required, current_user
from .. import db

main = Blueprint('main', __name__)


@main.route("/")
def index():
    return render_template("index.html", title="caesar博客")


@main.route('/article/<int:id>', methods=['GET', 'POST'])
def comments(id):
    article = Article.query.get_or_404(id)
    form = CommentForm(request.form)
    # 保存评论
    if form.validate_on_submit():
        comment = Comment(body=form.body.data, article_id=id, auther_id=current_user.id)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for(".comments", id=id))
    return render_template("article/details.html",
                           title=article.title,
                           form=form,
                           article=article)


@main.route('/edit', methods=['GET', 'POST'])
@main.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id=0):
    form = ArticleForm(request.form)
    if form.validate_on_submit():
        if id == 0:
            article = Article(user=current_user)
        else:
            article = Article.query.get_or_404(id)
        article.body = form.body.data
        article.title = form.title.data

        db.session.add(article)
        db.session.commit()
        # url_for调用处理函数函数名
        return redirect(url_for('.comments', id=article.id))

    title = u'添加文章'
    if id > 0:
        article = Article.query.get_or_404(id)
        form.body.data = article.body
        form.title.data = article.title
        title = u'编辑%s' % article.title

    return render_template('article/edit.html',
                           title=title,
                           form=form)


@main.route('/reply/<int:article_id>/<int:comment_id>', methods=['GET', 'POST'])
@login_required
def reply(article_id, comment_id):
    form = ReplyForm(request.form)
    if form.validate_on_submit():
        reply = Reply(comment_id=comment_id,auther_id=current_user.id)
        reply.body = form.body.data
        db.session.add(reply)
        db.session.commit()
        # url_for调用处理函数函数名
        return redirect(url_for('.comments', id=article_id))
    return render_template("article/reply.html", form=form)


@main.route('/about')
def about():
    return render_template('about.html', title=u'关于')

flask/database/database/app/templates/about.html
{% extends 'base.html' %}

flask/database/database/app/templates/article/details.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_body %}
    <div class="container">
        {# Meta 信息 #}
        <span>作者:{{ article.user.name }}</span> <span>发表日期:{{ article.created }}</span>

        {# 正文 #}
        <div>
            {{ article.body_html | safe }}
        </div>

        {# 操作链接 #}
        <h3>评论</h3>
        {# 发表评论 #}
        <div>
            {{ wtf.quick_form(form) }}
        </div>

        {# 评论列表 #}
        {% for comment in article.comments|sort(attribute='created',reverse=True ) %}
            <div class="media">
                <div class="media-body">
                    <small class="text-muted">{{loop.index}}楼{{ comment.user.name }}@{{ comment.created }}</small>
                    <div>{{ comment.body }}    <a href="{{url_for('main.reply', article_id=article.id, comment_id=comment.id)}}">回复</a></div>
                    {% for reply in comment.comments %}
                    <small class="text-muted">{{ reply.user.name }}回复{{comment.user.name}}  {{ reply.created }}</small>
                    <div>{{ reply.body }}    <a href="{{url_for('main.reply', article_id=article.id, comment_id=comment.id)}}">回复</a></div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

flask/database/database/app/templates/article/edit.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_body %}
    <div class="container">
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.title(class="form-group", placeholder="请输入标题") }}
            </div>
            <div class="form-group">
                {{ form.body(only_input=True,rows=10, class="form-group") }}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>

        </form>
    </div>
{% endblock %}

flask/database/database/app/templates/article/reply.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block page_body %}
    <div class="container">
        {% for message in get_flashed_messages() %}
           <div class="alert-info"> {{ message }}</div>
        {% endfor %}
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

flask/database/database/app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block head %}
    {{ super() }}
    {% include ['includes/_head.html'] %}
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/cerulean/bootstrap.min.css">
{% endblock %}

{% block navbar %}
    {% include 'includes/_navbar.html' %}
{% endblock %}

{% block content %}
    {% block header %}
        <header>
            <div class="page-header">
                <div class="container">
                    <h1>{{ title }}</h1>
                </div>
            </div>
        </header>
    {% endblock %}
    {% block page_body %}
    {% endblock %}
{% endblock %}

{% block footer %}
    <footer>
        Copyright 2020 by <a href="caesar.china.com">caesar</a>
    </footer>
{% endblock %}

flask/database/database/app/templates/includes/_head.html
<meta charset="UTF-8">
<link href="{{ url_for('static',filename='site.css') }}" rel="stylesheet">
<title>{% block title %}{% endblock %}</title>

flask/database/database/app/templates/includes/_navbar.html
<nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button aria-controls="navbar"
                    aria-expanded="false"
                    class="navbar-toggle collapsed"
                    data-target="#7bc75dbef69e41ff2452de70079c8ece1320ea7c"
                    data-toggle="collapse" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand">Flask入门</span>
        </div>
        <div class="navbar-collapse collapse"
             id="7bc75dbef69e41ff2452de70079c8ece1320ea7c">
            <ul class="nav navbar-nav">
                <li {% if url_for('main.index') is current_link %}class="active"{% endif %}>
                    <a href="{{ url_for('main.index') }}" title="主页">主页</a>
                </li>
                <li {% if url_for('main.edit') is current_link %}class="active"{% endif %}>
                    <a href="{{ url_for('main.edit') }}" title="新文章">新文章</a>
                </li>
                <li {% if url_for('main.about') is current_link %}class="active"{% endif %}>
                    <a href="{{ url_for('main.about') }}" title="关于">关于我</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                    <li><a href="#">{{ current_user.name }}</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">退出</a></li>
                {% else %}
                    <li><a href="{{ url_for('auth.login') }}">登录</a></li>
                    <li><a href="{{ url_for('auth.register') }}">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

flask/database/database/app/templates/index.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% block content %}
  <div class="page-header">
    <div class="container">
        {{ title }}
    </div>
  </div>
{% endblock %}
</body>
</html>

flask/database/database/app/templates/login.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% block content %}
{# <form method="post" action="/login">#}
{#     <div>#}
{#         <input type="text"#}
{#                name="username"#}
{#                placeholder="user name" />#}
{#     </div>#}
{#     <div>#}
{#         <input type="password"#}
{#                name="password">#}
{#     </div>#}
{#     <input type="submit">#}
{# </form>#}
<form method="post">
    <div>
        {% for field in form %}
            {% if loop.last %}
                {{ field }}
            {% else %}
                {{ field.label }}
                {{ field }}
            {% endif %}
        {% endfor %}

{#        {{ form.username.label }}#}
{#        {{ form.username }}#}
{#        {{ form.password.label }}#}
{#        {{ form.password() }}#}
{#        {{ form.submit() }}#}
    </div>
</form>
{% endblock %}
</body>
</html>

flask/database/database/app/templates/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf  %}
{% block page_body %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert-info"> {{ message }}</div>
        {% endfor %}
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

flask/database/database/app/templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <form method="post" action="/upload" enctype="multipart/form-data">
        <div>
            <input type="file" name="file">
        </div>
        <input type="submit" value="上传"/>
    </form>

</body>
</html>